services:
  wordpress:
    container_name: my_wp
    build: ./wordpress
    volumes:
      - wp_data:/var/www/html
    networks:
      - wp-network
    depends_on:
      - mariadb

  nginx:
    container_name: my_nginx
    build: ./nginx
    volumes:
      - wp_data:/var/www/html
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - wp-network
  
  mariadb:
    container_name: my_mariadb
    build: ./mariadb
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp-network

networks:
  wp-network:
    driver: bridge
  
volumes:
  wp_data:
  db_data:

