services:
  wordpress:
    container_name: my_wp
    environment:
      WP_URL: ${WP_URL}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
    build:
      context: ./wordpress
    volumes:
      - wp_data:/var/www/html
    networks:
      - wp-network
    depends_on:
      - mariadb
    restart: always

  nginx:
    container_name: my_nginx
    build:
      context: ./nginx
    volumes:
      - wp_data:/var/www/html
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      #- "80:80"
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - wp-network
    restart: always
  
  mariadb:
    container_name: my_mariadb
    build:
      context: ./mariadb
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp-network
    restart: always

networks:
  wp-network:
    driver: bridge
 
volumes:
  wp_data:
    name: wp_data
    driver: local
    driver_opts:
      device: /home/kohshi54/data//wp_data/
      o: bind
      type: none
  db_data:
    name: db_data
    driver: local
    driver_opts:
      device: /home/kohshi54/data/db_data/
      o: bind
      type: none

