services:
  wordpress:
    container_name: wp-ct
    env_file:
      - .env
    image: wordpress:42
    build: ./wordpress
    volumes:
      - wp_data:/var/www/html
    networks:
      - wp-network
    depends_on:
      - mariadb
    restart: always

  nginx:
    container_name: nginx-ct
    image: nginx:42
    build: ./nginx
    volumes:
      - wp_data:/var/www/html
      #- ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      #- "80:80"
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - wp-network
    restart: always
  
  mariadb:
    container_name: mariadb-ct
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    image: mariadb:42
    build: ./mariadb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp-network
    restart: always

networks:
  wp-network:
    name: wp-network
    driver: bridge
 
volumes:
  wp_data:
    name: wp_data
    driver: local
    driver_opts:
      device: ~/data/wp_data/
      o: bind
      type: none
  db_data:
    name: db_data
    driver: local
    driver_opts:
      device: ~/data/db_data/
      o: bind
      type: none

