
services:
  mariadb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mariadb-container
    environment:
      MARIADB_ROOT_PASSWORD: my-secret-pw
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
    driver: local

